// Estado do módulo: forms
export const state = {
  // Configurações Gerais do Aviário (Moçambique)
      settings: {
        farmName: 'Aviário Inteligente Pro',
        tagline: 'Sistema Integrado de Gestão Avícola & Produção',
        ownerName: '',
        phone: '',
        location: '',
        currency: 'MT',
        targetFCR: 1.60,
        maxMortalityPercent: 3.0,
        cycleDays: 38,
        standardWeightTarget: 2.10,
        feedBagsWeightKg: 50,
        alertLowStock: true,
        alertHighMortality: true,
        alertOverdueDebt: true,
        companyLegalName: '',
        companySubtitle: 'Sistema Integrado de Gestão Avícola & Produção',
        companyAddress: '',
        companyEmail: '',
        companyLogo: '',
        reportFooter: '',
        signatureName: '',
        signatureTitle: '',
        signatureImage: ''
      },
  // Variáveis de Estado - Lotes de Frangos Pro
      loteSearch: '',
  loteStatusFilter: 'active',
  selectedLote: null,
  loteDetailTab: 'resumo',
  showNewLote: false,
  newLoteCode: '',
  newLoteBreed: 'Frango de corte',
  newLoteEntryDate: '',
  newLoteBirds: '',
  newLoteAvgWeight: '',
  newLoteNotes: '',
  newLoteSupplier: '',
  newLoteInitialAge: 1,
  newLotePricePerChick: '',
  newLoteCostChicks: 0,
  // Pesagem Form
      newWeightDate: '',
  newWeightKg: '',
  newWeightAgeDays: '',
  // Variáveis de Estado - Caixa & Finanças Pro
      finFilterPeriod: 'month',
  showModalEntrada: false,
  showModalSaida: false,
  showModalPagamento: false,
  // Nova Entrada Form
      newEntradaType: 'Venda',
  newEntradaDesc: '',
  newEntradaAmount: '',
  newEntradaClientId: '',
  newEntradaClientName: '',
  newEntradaDate: '',
  newEntradaMethod: 'M-Pesa',
  newEntradaObs: '',
  newEntradaProof: '',
  // Nova Saída Form
      newSaidaCategory: 'Ração',
  newSaidaDesc: '',
  newSaidaAmount: '',
  newSaidaBagsQty: '',
  newSaidaStockItemId: '',
  newSaidaDate: '',
  newSaidaMethod: 'Dinheiro',
  newSaidaStatus: 'Pago',
  // Saúde, medicamentos e vacinação
  healthLogs: [],
  showHealthModal: false,
  newHealthLoteId: '',
  newHealthType: 'Vacinação',
  newHealthDate: '',
  newHealthProduct: '',
  newHealthQty: '',
  newHealthCost: '',
  newHealthNextDate: '',
  newHealthNotes: '',
  // Pagamento de Dívida Form
      newPayClientId: '',
  newPayAmount: '',
  newPayMethod: 'M-Pesa',
  newPayDate: '',
  newPayNotes: '',
  // Sub-abas de Inventário & Stock
      stockSubTab: 'produtos',
  stockSearch: '',
  stockCategoryFilter: 'ALL',
  expenses: [],
  attendance: [],
  notifications: [],
  priceTable: [],
  // Formulários de Login & Cadastro
      loginUsername: '',
  loginSenha: '',
  rememberMe: true,
  authBusy: false,
  operationBusy: false,
  operationLabel: '',
  operationStep: '',
  loginError: '',
  showSignup: false,
  suNome: '',
  suUsername: '',
  suEmail: '',
  suSenha: '',
  suSenhaConfirm: '',
  suCredentialType: 'password',
  suPin: '',
  suPinConfirm: '',
  suFarmName: '',
  signupError: '',
  // Form Morte
      newMortLoteId: '',
  newMortDate: '',
  newMortQty: '',
  newMortReason: 'Normal / Maneio',
  // Form Ração
      newFeedLoteId: '',
  newFeedDate: '',
  newFeedType: 'Ração A1 (Inicial 0-14d)',
  newFeedMovement: 'CONSUMO',
  newFeedQtyKg: '',
  newFeedPriceBag: '',
  newFeedSupplier: '',
  newFeedTurno: 'Manhã',
  // Form Venda
      newSaleLoteId: '',
  newSaleClientId: '',
  newSaleClientName: '',
  newSaleDate: '',
  newSaleProduct: 'Frango Vivo',
  newSaleType: 'unit',
  newSaleQty: '',
  newSaleWeightKg: '',
  newSalePriceUnit: '',
  newSalePaidAmount: '',
  newSalePaymentMethod: 'Dinheiro',
  newSalePaymentStatus: 'Pago',
  // Form Cliente
      newClientName: '',
  newClientPhone: '',
  newClientAddress: '',
  newClientType: 'Restaurante / Hotel',
  // Form Despesa
      newExpLoteId: '',
  newExpCategory: 'Medicamentos & Vacinas',
  newExpDesc: '',
  newExpAmount: '',
  newExpDate: '',
  newExpPaymentMethod: 'Caixa / Numerário',
  // Form Energia
      newEnergyPrev: '',
  newEnergyCurr: '',
  newEnergyPriceKwh: '',
  newEnergyAmount: '',
  newEnergyDate: '',
  // Form Colaborador
      newStaffName: '',
  newStaffPhone: '',
  newStaffEmail: '',
  newStaffRoleType: 'employee',
  newStaffSalary: '',
  showSalaryPaymentModal: false,
  salaryPaymentStaff: null,
  salaryPaymentAmount: '',
  salaryPaymentDescription: 'Pagamento de salário',
  salaryPaymentMethod: 'Caixa / Numerário',
  editingAccessUser: null,
  accessEditRoleType: 'employee',
  accessEditStatus: 'active',
  // Form Ponto
      pontoStaffId: '',
  pontoStatus: 'present',
  pontoCheckIn: '07:00',
  pontoCheckOut: '17:00',
  pontoNotes: '',
  // Form Stock
      newStockName: '',
  newStockCategory: 'Ração',
  newStockQty: '',
  newStockUnit: 'Sacos 50kg',
  newStockMin: '',
  newStockPrice: '',
  newStockSupplier: '',
  newStockExpiry: '',
  newStockLot: 'LOT-2026-A',
  cloudSyncPending: false,
  cloudSyncError: '',
};
